### ISSUE TITLE
error processing package stellar-horizon-postgres (--configure)

### ISSUE THREAD

**Issue by Cheny-chen** [stellar/packages#48] opened 2019-04-27 04:42 UTC
### I install quickstart and get the following errows
Ehe vultr vm  is  ubuntu 16.04 server and postgresql 9.5

```
dpkg: error processing package stellar-horizon-postgres (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of stellar-quickstart:
 stellar-quickstart depends on stellar-horizon-postgres; however:
  Package stellar-horizon-postgres is not configured yet.

dpkg: error processing package stellar-quickstart (--configure):
 dependency problems - leaving unconfigured
No apport report written because the error message indicates its a followup error from a previous failure.
                                                                                                          Errors were encountered while processing:
 stellar-horizon-postgres
 stellar-quickstart
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

### however, when I access db, horizon db is exist
```
# sudo -u stellar psql -d stellar
could not change directory to "/root": Permission denied
psql (9.5.16)
Type "help" for help.

stellar=> \l
                                  List of databases
   Name    |  Owner   | Encoding |   Collate   |    Ctype    |   Access privileges   
-----------+----------+----------+-------------+-------------+-----------------------
 horizon   | stellar  | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 postgres  | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 stellar   | stellar  | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 template0 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
           |          |          |             |             | postgres=CTc/postgres
 template1 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
           |          |          |             |             | postgres=CTc/postgres
(5 rows)
```

### Then, I check if tables is exites
```
stellar=> \dt
             List of relations
 Schema |      Name      | Type  |  Owner  
--------+----------------+-------+---------
 public | accountdata    | table | stellar
 public | accounts       | table | stellar
 public | ban            | table | stellar
 public | ledgerheaders  | table | stellar
 public | offers         | table | stellar
 public | peers          | table | stellar
 public | publishqueue   | table | stellar
 public | pubsub         | table | stellar
 public | quoruminfo     | table | stellar
 public | scphistory     | table | stellar
 public | scpquorums     | table | stellar
 public | storestate     | table | stellar
 public | trustlines     | table | stellar
 public | txfeehistory   | table | stellar
 public | txhistory      | table | stellar
 public | upgradehistory | table | stellar
(16 rows)
```

**Comment by Cheny-chen** [comment] 2019-04-27 05:08
I finally found the solution
https://stellar.stackexchange.com/questions/2398/how-to-configure-package-stellar-horizon-postgres
```
$  sudo -u stellar psql -c 'DROP DATABASE horizon' postgres
$  sudo apt-get update && sudo apt-get install stellar-horizon
$  sudo -u stellar psql -d horizon
$  sudo systemctl unmask stellar-core
$  sudo systemctl start stellar-core
$  sudo stellar-core-cmd info
$ sudo systemctl start stellar-horizon
$  sudo systemctl status stellar-horizon
```

**Comment by brahman81** [comment] 2019-04-29 15:39
This is a duplicate of https://github.com/stellar/packages/issues/42.

Issue is resolved. Closing.

**Closed by brahman81** 2019-04-29 15:39 UTC
